import React, { createContext, useState, useContext, useEffect } from 'react';

// ============ TRANSLATIONS ============
const translations = {
  en: {
    // Common
    appName: 'Maid & Nanny Platform',
    welcome: 'Welcome',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    dashboard: 'Dashboard',
    profile: 'Profile',
    browse: 'Browse Helpers',
    search: 'Search',
    filters: 'Filters',
    clearAll: 'Clear All',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    viewAll: 'View All',
    back: 'Back',
    email: 'Email Address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    phone: 'Phone Number',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    createAccount: 'Create Account',
    welcomeBack: 'Welcome Back!',
    totalBookings: 'Total Bookings',
    pending: 'Pending',
    active: 'Active',
    completed: 'Completed',
    cancelled: 'Cancelled',
    myBookings: 'My Bookings',
    noBookings: 'No bookings yet',
    findHelpers: 'Find Helpers',
    needHelp: 'Need Help? Find a Helper!',
    helpers: 'Helpers',
    totalHelpers: 'Total Helpers',
    verifiedHelpers: 'Verified Helpers',
    pendingVerification: 'Pending Verification',
    available: 'Available',
    unavailable: 'Unavailable',
    experience: 'Experience',
    years: 'years',
    rating: 'Rating',
    reviews: 'reviews',
    viewProfile: 'View Profile',
    bookNow: 'Book Now',
    serviceType: 'Service Type',
    skills: 'Skills',
    languages: 'Languages',
    about: 'About',
    contact: 'Contact',
    availability: 'Availability',
    workingDays: 'Working Days',
    workingHours: 'Working Hours',
    startTime: 'Start Time',
    endTime: 'End Time',
    createBooking: 'Create Booking',
    bookingDetails: 'Booking Details',
    serviceDate: 'Service Date',
    specialInstructions: 'Special Instructions',
    address: 'Address',
    confirmBooking: 'Confirm Booking',
    payment: 'Payment',
    payNow: 'Pay Now',
    amount: 'Amount',
    paymentMethod: 'Payment Method',
    card: 'Credit/Debit Card',
    upi: 'UPI',
    netbanking: 'Net Banking',
    platformFee: 'Platform Fee',
    total: 'Total',
    adminDashboard: 'Admin Dashboard',
    manageHelpers: 'Manage Helpers',
    manageUsers: 'Manage Users',
    viewBookings: 'View Bookings',
    viewReviews: 'View Reviews',
    viewAnalytics: 'View Analytics',
    managePayments: 'Manage Payments',
    recentHelpers: 'Recent Helpers',
    recentReviews: 'Recent Reviews',
    recentBookings: 'Recent Bookings',
    attendance: 'Attendance',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    leave: 'Leave',
    applyLeave: 'Apply Leave',
    leaveType: 'Leave Type',
    sick: 'Sick',
    casual: 'Casual',
    annual: 'Annual',
    emergency: 'Emergency',
    other: 'Other',
    reason: 'Reason',
    status: 'Status',
    approved: 'Approved',
    rejected: 'Rejected',
    present: 'Present',
    absent: 'Absent',
    halfDay: 'Half Day',
    sos: 'SOS',
    sosAlert: 'SOS Alert Sent!',
    sosDescription: 'Emergency alert sent to your contacts',
    addContacts: 'Add Emergency Contacts',
    contactName: 'Contact Name',
    contactPhone: 'Contact Phone',
    errorOccurred: 'An error occurred',
    tryAgain: 'Please try again',
    noResults: 'No results found',
    requiredField: 'This field is required',
    invalidEmail: 'Please enter a valid email',
    passwordMismatch: 'Passwords do not match',
    passwordMinLength: 'Password must be at least 6 characters',
    getStarted: 'Get Started',
    trustedConnection: 'Your trusted connection to verified domestic helpers',
    findPerfectHelper: 'Find Your Perfect Helper',
    browseDesc: 'Browse verified and trusted domestic helpers in your area',
    searchByName: 'Search by name, skills, or keywords...',
    selectService: 'Select a helper',
    totalEarnings: 'Total Earnings',
    wantMoreWork: 'Want More Work?',
    updateAvailability: 'Update your availability and get more bookings',
    updateProfile: 'Update Profile',
    myProfile: 'My Profile',
    noHelpers: 'No helpers found',
    noData: 'No data available',
    welcomeAdmin: 'Welcome, Admin',
    totalUsers: 'Total Users',
    manageSOS: 'Manage SOS',
    leaveHistory: 'Leave History',
    attendanceHistory: 'History',
    contactRelationship: 'Relationship',
    primaryContact: 'Primary',
    addContact: 'Add Contact',
    triggerSOS: 'Trigger SOS',
    sosButtonDesc: 'Tap again to cancel',
    sosSent: 'SOS Alert Sent!',
    sosNotified: 'Emergency contacts have been notified with your location.',
    gotIt: 'Got it',
    checkInSuccess: 'Checked in successfully!',
    checkOutSuccess: 'Checked out successfully! Hours calculated.',
    applyLeaveSuccess: 'Leave application submitted successfully!',
    leaveApproved: 'Leave approved successfully!',
    leaveRejected: 'Leave rejected successfully!',
    paymentSuccess: 'Payment completed successfully!',
    reviewSubmitted: 'Review submitted successfully!',
    bookingCreated: 'Booking created successfully!',
    bookingAccepted: 'Booking accepted successfully!',
    bookingCompleted: 'Booking completed successfully!',
    bookingCancelled: 'Booking cancelled successfully!',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    signingIn: 'Signing in...',
    dontHaveAccount: "Don't have an account?",
    signUpNow: 'Sign up now',
    joinCommunity: 'Join our trusted community today',
    iAm: 'I am a',
    household: 'Household (Looking for help)',
    helper: 'Helper (Looking for work)',
    agreeToTerms: 'I agree to the',
    termsOfService: 'Terms of Service',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    creatingAccount: 'Creating account...',
    alreadyHaveAccount: 'Already have an account?',
    agreeTermsRequired: 'Please agree to the Terms and Conditions',
    signOut: 'Sign Out',
    cancelBooking: 'Cancel Booking',
    confirmCancel: 'Are you sure you want to cancel this booking?',
    deleteAccount: 'Delete Account',
    confirmDelete: 'Are you sure you want to delete your account?',
    noRecords: 'No records found',
    applyNow: 'Apply Now',
    submit: 'Submit',
    processing: 'Processing...',
    success: 'Success!',
    error: 'Error!',
    warning: 'Warning!',
    info: 'Info',
    close: 'Close',
    next: 'Next',
    previous: 'Previous',
    finish: 'Finish',
    start: 'Start',
    stop: 'Stop',
    pause: 'Pause',
    resume: 'Resume',
    refresh: 'Refresh',
    reload: 'Reload',
    update: 'Update',
    add: 'Add',
    remove: 'Remove',
    view: 'View',
    edit: 'Edit',
    print: 'Print',
    download: 'Download',
    upload: 'Upload',
    share: 'Share',
    copy: 'Copy',
    paste: 'Paste',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    expand: 'Expand',
    collapse: 'Collapse',
    showMore: 'Show More',
    showLess: 'Show Less',
    readMore: 'Read More',
    readLess: 'Read Less',
    learnMore: 'Learn More',
    contactUs: 'Contact Us',
    aboutUs: 'About Us',
    help: 'Help',
    support: 'Support',
    feedback: 'Feedback',
    report: 'Report',
    settings: 'Settings',
    preferences: 'Preferences',
    notifications: 'Notifications',
    security: 'Security',
    privacy: 'Privacy',
    terms: 'Terms',
    cookies: 'Cookies',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    welcomeMessage: 'Welcome to Maid & Nanny Platform',
    loadingMessage: 'Please wait while we load your data...',
    noInternet: 'No internet connection. Please check your network.',
    retry: 'Retry',
    offline: 'Offline',
    online: 'Online',
    pleaseWait: 'Please wait...',
    thankYou: 'Thank you!',
    congratulations: 'Congratulations!',
    goodJob: 'Good job!',
    wellDone: 'Well done!',
    excellent: 'Excellent!',
    amazing: 'Amazing!',
    awesome: 'Awesome!',
    great: 'Great!',
    nice: 'Nice!',
    perfect: 'Perfect!',
    wonderful: 'Wonderful!',
  },
  hi: {
    // Common
    appName: 'मेड एंड नैनी प्लेटफॉर्म',
    welcome: 'स्वागत है',
    login: 'लॉग इन',
    register: 'पंजीकरण',
    logout: 'लॉग आउट',
    dashboard: 'डैशबोर्ड',
    profile: 'प्रोफ़ाइल',
    browse: 'सहायक खोजें',
    search: 'खोजें',
    filters: 'फ़िल्टर',
    clearAll: 'सभी साफ़ करें',
    loading: 'लोड हो रहा है...',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    viewAll: 'सभी देखें',
    back: 'पीछे',
    email: 'ईमेल पता',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    fullName: 'पूरा नाम',
    phone: 'फोन नंबर',
    signIn: 'साइन इन करें',
    signUp: 'साइन अप करें',
    createAccount: 'खाता बनाएं',
    welcomeBack: 'वापसी पर स्वागत है!',
    totalBookings: 'कुल बुकिंग',
    pending: 'लंबित',
    active: 'सक्रिय',
    completed: 'पूर्ण',
    cancelled: 'रद्द',
    myBookings: 'मेरी बुकिंग',
    noBookings: 'अभी कोई बुकिंग नहीं',
    findHelpers: 'सहायक खोजें',
    needHelp: 'मदद चाहिए? सहायक खोजें!',
    helpers: 'सहायक',
    totalHelpers: 'कुल सहायक',
    verifiedHelpers: 'सत्यापित सहायक',
    pendingVerification: 'लंबित सत्यापन',
    available: 'उपलब्ध',
    unavailable: 'अनुपलब्ध',
    experience: 'अनुभव',
    years: 'साल',
    rating: 'रेटिंग',
    reviews: 'समीक्षाएं',
    viewProfile: 'प्रोफ़ाइल देखें',
    bookNow: 'अभी बुक करें',
    serviceType: 'सेवा प्रकार',
    skills: 'कौशल',
    languages: 'भाषाएं',
    about: 'परिचय',
    contact: 'संपर्क',
    availability: 'उपलब्धता',
    workingDays: 'कार्य दिवस',
    workingHours: 'कार्य घंटे',
    startTime: 'प्रारंभ समय',
    endTime: 'समाप्ति समय',
    createBooking: 'बुकिंग करें',
    bookingDetails: 'बुकिंग विवरण',
    serviceDate: 'सेवा तिथि',
    specialInstructions: 'विशेष निर्देश',
    address: 'पता',
    confirmBooking: 'बुकिंग की पुष्टि करें',
    payment: 'भुगतान',
    payNow: 'अभी भुगतान करें',
    amount: 'राशि',
    paymentMethod: 'भुगतान विधि',
    card: 'क्रेडिट/डेबिट कार्ड',
    upi: 'यूपीआई',
    netbanking: 'नेट बैंकिंग',
    platformFee: 'प्लेटफॉर्म शुल्क',
    total: 'कुल',
    adminDashboard: 'एडमिन डैशबोर्ड',
    manageHelpers: 'सहायक प्रबंधित करें',
    manageUsers: 'उपयोगकर्ता प्रबंधित करें',
    viewBookings: 'बुकिंग देखें',
    viewReviews: 'समीक्षाएं देखें',
    viewAnalytics: 'एनालिटिक्स देखें',
    managePayments: 'भुगतान प्रबंधित करें',
    recentHelpers: 'हाल के सहायक',
    recentReviews: 'हाल की समीक्षाएं',
    recentBookings: 'हाल की बुकिंग',
    attendance: 'उपस्थिति',
    checkIn: 'चेक इन',
    checkOut: 'चेक आउट',
    leave: 'अवकाश',
    applyLeave: 'अवकाश आवेदन करें',
    leaveType: 'अवकाश प्रकार',
    sick: 'बीमारी',
    casual: 'सामान्य',
    annual: 'वार्षिक',
    emergency: 'आपातकालीन',
    other: 'अन्य',
    reason: 'कारण',
    status: 'स्थिति',
    approved: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    present: 'उपस्थित',
    absent: 'अनुपस्थित',
    halfDay: 'आधा दिन',
    sos: 'एसओएस',
    sosAlert: 'एसओएस अलर्ट भेजा गया!',
    sosDescription: 'आपातकालीन अलर्ट आपके संपर्कों को भेजा गया',
    addContacts: 'आपातकालीन संपर्क जोड़ें',
    contactName: 'संपर्क नाम',
    contactPhone: 'संपर्क फोन',
    errorOccurred: 'एक त्रुटि हुई',
    tryAgain: 'कृपया पुनः प्रयास करें',
    noResults: 'कोई परिणाम नहीं मिला',
    requiredField: 'यह फ़ील्ड आवश्यक है',
    invalidEmail: 'कृपया एक मान्य ईमेल दर्ज करें',
    passwordMismatch: 'पासवर्ड मेल नहीं खाते',
    passwordMinLength: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    getStarted: 'शुरू करें',
    trustedConnection: 'सत्यापित घरेलू सहायकों से आपका भरोसेमंद कनेक्शन',
    findPerfectHelper: 'अपना सही सहायक खोजें',
    browseDesc: 'अपने क्षेत्र में सत्यापित और भरोसेमंद सहायकों को ब्राउज़ करें',
    searchByName: 'नाम, कौशल, या कीवर्ड से खोजें...',
    selectService: 'सहायक चुनें',
    totalEarnings: 'कुल कमाई',
    wantMoreWork: 'अधिक काम चाहिए?',
    updateAvailability: 'अपनी उपलब्धता अपडेट करें और अधिक बुकिंग प्राप्त करें',
    updateProfile: 'प्रोफ़ाइल अपडेट करें',
    myProfile: 'मेरी प्रोफ़ाइल',
    noHelpers: 'कोई सहायक नहीं मिला',
    noData: 'कोई डेटा उपलब्ध नहीं',
    welcomeAdmin: 'स्वागत है, एडमिन',
    totalUsers: 'कुल उपयोगकर्ता',
    manageSOS: 'एसओएस प्रबंधित करें',
    leaveHistory: 'अवकाश इतिहास',
    attendanceHistory: 'इतिहास',
    contactRelationship: 'संबंध',
    primaryContact: 'प्राथमिक',
    addContact: 'संपर्क जोड़ें',
    triggerSOS: 'एसओएस ट्रिगर करें',
    sosButtonDesc: 'रद्द करने के लिए फिर से टैप करें',
    sosSent: 'एसओएस अलर्ट भेजा गया!',
    sosNotified: 'आपातकालीन संपर्कों को आपके स्थान के साथ सूचित किया गया है।',
    gotIt: 'समझ गया',
    checkInSuccess: 'चेक इन सफल!',
    checkOutSuccess: 'चेक आउट सफल! घंटे गणना की गई।',
    applyLeaveSuccess: 'अवकाश आवेदन सफलतापूर्वक जमा किया गया!',
    leaveApproved: 'अवकाश स्वीकृत!',
    leaveRejected: 'अवकाश अस्वीकृत!',
    paymentSuccess: 'भुगतान सफलतापूर्वक पूरा हुआ!',
    reviewSubmitted: 'समीक्षा सफलतापूर्वक जमा की गई!',
    bookingCreated: 'बुकिंग सफलतापूर्वक बनाई गई!',
    bookingAccepted: 'बुकिंग स्वीकार कर ली गई!',
    bookingCompleted: 'बुकिंग पूर्ण हुई!',
    bookingCancelled: 'बुकिंग रद्द कर दी गई!',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    signingIn: 'साइन इन हो रहा है...',
    dontHaveAccount: 'खाता नहीं है?',
    signUpNow: 'अभी साइन अप करें',
    joinCommunity: 'हमारे भरोसेमंद समुदाय में शामिल हों',
    iAm: 'मैं हूँ',
    household: 'परिवार (सहायक की तलाश में)',
    helper: 'सहायक (काम की तलाश में)',
    agreeToTerms: 'मैं सहमत हूँ',
    termsOfService: 'सेवा की शर्तें',
    and: 'और',
    privacyPolicy: 'गोपनीयता नीति',
    creatingAccount: 'खाता बना रहा है...',
    alreadyHaveAccount: 'पहले से खाता है?',
    agreeTermsRequired: 'कृपया सेवा की शर्तों से सहमत हों',
    signOut: 'साइन आउट',
    cancelBooking: 'बुकिंग रद्द करें',
    confirmCancel: 'क्या आप वाकई इस बुकिंग को रद्द करना चाहते हैं?',
    deleteAccount: 'खाता हटाएं',
    confirmDelete: 'क्या आप वाकई अपना खाता हटाना चाहते हैं?',
    noRecords: 'कोई रिकॉर्ड नहीं मिला',
    applyNow: 'अभी आवेदन करें',
    submit: 'जमा करें',
    processing: 'प्रोसेस हो रहा है...',
    success: 'सफल!',
    error: 'त्रुटि!',
    warning: 'चेतावनी!',
    info: 'जानकारी',
    close: 'बंद करें',
    next: 'अगला',
    previous: 'पिछला',
    finish: 'समाप्त',
    start: 'शुरू',
    stop: 'रोकें',
    pause: 'रोकें',
    resume: 'फिर से शुरू',
    refresh: 'रिफ्रेश',
    reload: 'रीलोड',
    update: 'अपडेट',
    add: 'जोड़ें',
    remove: 'हटाएं',
    view: 'देखें',
    print: 'प्रिंट',
    download: 'डाउनलोड',
    upload: 'अपलोड',
    share: 'शेयर',
    copy: 'कॉपी',
    paste: 'पेस्ट',
    selectAll: 'सभी चुनें',
    deselectAll: 'सभी अचुनें',
    expand: 'विस्तार करें',
    collapse: 'संक्षिप्त करें',
    showMore: 'और दिखाएं',
    showLess: 'कम दिखाएं',
    readMore: 'और पढ़ें',
    readLess: 'कम पढ़ें',
    learnMore: 'और जानें',
    contactUs: 'संपर्क करें',
    aboutUs: 'हमारे बारे में',
    help: 'सहायता',
    support: 'सहायता',
    feedback: 'प्रतिक्रिया',
    report: 'रिपोर्ट',
    settings: 'सेटिंग्स',
    preferences: 'प्राथमिकताएं',
    notifications: 'सूचनाएं',
    security: 'सुरक्षा',
    privacy: 'गोपनीयता',
    terms: 'शर्तें',
    cookies: 'कुकीज़',
    language: 'भाषा',
    theme: 'थीम',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    welcomeMessage: 'मेड एंड नैनी प्लेटफॉर्म में आपका स्वागत है',
    loadingMessage: 'कृपया प्रतीक्षा करें जब तक हम आपका डेटा लोड करें...',
    noInternet: 'कोई इंटरनेट कनेक्शन नहीं। कृपया अपना नेटवर्क जांचें।',
    retry: 'पुनः प्रयास करें',
    offline: 'ऑफलाइन',
    online: 'ऑनलाइन',
    pleaseWait: 'कृपया प्रतीक्षा करें...',
    thankYou: 'धन्यवाद!',
    congratulations: 'बधाई हो!',
    goodJob: 'अच्छा काम!',
    wellDone: 'शाबाश!',
    excellent: 'उत्कृष्ट!',
    amazing: 'अद्भुत!',
    awesome: 'शानदार!',
    great: 'बहुत अच्छा!',
    nice: 'अच्छा!',
    perfect: 'परफेक्ट!',
    wonderful: 'अद्भुत!',
  },
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  const [t, setT] = useState(translations[language] || translations.en);

  useEffect(() => {
    localStorage.setItem('language', language);
    setT(translations[language] || translations.en);
  }, [language]);

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  const value = {
    language,
    t,
    changeLanguage,
    availableLanguages: Object.keys(translations),
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;